server:
  port: 10000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gulimall_pms
    username: root
    password: 20020327
  cache:
    type: redis
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gulimall-product
  thymeleaf:
    cache: false
  redis:
    host: localhost
    port: 6379
    database: 2
  session:
    store-type: redis

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
logging:
  level:
    top.integer.gulimall: debug
