spring:
  application:
    name: gulimall-auth-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  thymeleaf:
    cache: false
  redis:
    host: localhost
    port: 6379
    database: 2
  session:
    store-type: redis

server:
  port: 8200
  servlet:
    session:
      timeout: 36000

