server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gulimall_oms
    username: root
    password: 20020327
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gulimall-order
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
