server:
  port: 9000
  servlet:
    session:
      timeout: 36000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gulimall_oms
    username: root
    password: 20020327
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gulimall-order
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        concurrency: 3
        acknowledge-mode: manual
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
  redis:
    host: localhost
    port: 6379
    database: 2
  session:
    store-type: redis
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
