server:
  port: 31000

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gulimall-cart
  redis:
    host: localhost
    port: 6379
    database: 2
  session:
    store-type: redis
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
