server:
  port: 11000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gulimall_wms
    username: root
    password: 20020327
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gulimall-ware
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
logging:
  level:
    top.integer.gulimall.ware.dao: debug
